### ISSUE TITLE
Issue with simple Proxy Project -java.lang.NoSuchMethodError: com.github.mkopylec.charon.configuration.CharonConfiguration: method <init>()V not found

### ISSUE THREAD

**Issue by lefty-kreouzis** [mkopylec/charon-spring-boot-starter#106]
I created a simple maven project for an http proxy using the sprin-boot-web

I added dependencies for the charon-spring webmvc and boot-starter

		<dependency>
			<groupId>com.github.mkopylec</groupId>
			<artifactId>charon-spring-boot-starter</artifactId>
			<version>3.2.0</version>
		</dependency>
		<dependency>
			<groupId>com.github.mkopylec</groupId>
			<artifactId>charon-spring-webmvc</artifactId>
			<version>4.6.0</version>
		</dependency>

Created a simple HTTPConfiguration class
@Configuration
@ComponentScan("ae.etisalat")
@PropertySource("classpath:application.properties")
@PropertySource(ignoreResourceNotFound = true, value="classpath:git.properties")
class HTTPConfiguration {
	
	@Autowired
	Environment env;
	
	@Bean
    CharonConfigurer charonConfigurer() 
	{
		String hostURL = env.getProperty("host.url");
		
		CharonConfigurer charonConfigurer = CharonConfigurer.charonConfiguration();
		return charonConfigurer
                .set(requestServerNameRewriter().outgoingServers(hostURL))
                .add(requestMapping("all requests mapping"));
    }

}

The project compiles fine but when it tries to start it fails with an exception

Caused by: java.lang.NoSuchMethodError: com.github.mkopylec.charon.configuration.CharonConfiguration: method <init>()V not found
	at com.github.mkopylec.charon.configuration.CharonConfigurer.<init>(CharonConfigurer.java:14) ~[charon-spring-webmvc-4.6.0.jar:na]
	at com.github.mkopylec.charon.configuration.CharonConfigurer.charonConfiguration(CharonConfigurer.java:18) ~[charon-spring-webmvc-4.6.0.jar:na]
	at ae.etisalat.proxy.HTTPConfiguration.charonConfigurer(HTTPConfiguration.java:30) ~[classes/:na]
	at ae.etisalat.proxy.HTTPConfiguration$$EnhancerBySpringCGLIB$$a555812a.CGLIB$charonConfigurer$0(<generated>) ~[classes/:na]
	at ae.etisalat.proxy.HTTPConfiguration$$EnhancerBySpringCGLIB$$a555812a$$FastClassBySpringCGLIB$$54d3274.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at ae.etisalat.proxy.HTTPConfiguration$$EnhancerBySpringCGLIB$$a555812a.charonConfigurer(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_251]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]

**Comment by lefty-kreouzis** [comment]
Found the issue....

I shouldn't have explicitly added the charon-spring-boot-starter dependency

AFter removing it and just keeping the charon-spring-webmvc dependency it compiles and runs

Lefty

**Comment by mkopylec** [comment]
Glad to hear 🙂
